class UserModel {
  static Map<String, dynamic> user = {
    'name': "Hannibal Lector",
    'email': "hannibal@gmail.com",
    'image':
        "assets/img/doctor/934723-2560x1600-desktop-hd-hannibal-mads-mikkelsen-background.jpg",
  };

  static List<dynamic> doctors = [
    {
      'name': "Xwncha Rahman",
      'specialty': "Cardiologist",
      'degree': "MBBS/MD",
      'hospital': "Charité – Universitätsmedizin Berlin",
      'location': "Germany - Berlin",
      'image': "female-doctor-hospital-with-stethoscope.jpg",
      'response': "pending",
    },
    {
      'name': "Sabah Kalary",
      'specialty': "Radiologist",
      'degree': "MBBS/MD",
      'hospital': "Charité – Universitätsmedizin Berlin",
      'location': "Germany - Berlin",
      'image':
          "attractive-young-male-nutriologist-lab-coat-smiling-against-white-background.jpg",
      'response': "rejected",
    },
    {
      'name': "Sardar Kareem",
      'specialty': "Hematologist",
      'degree': "MBBS/MD",
      'hospital': "Charité – Universitätsmedizin Berlin",
      'location': "Germany - Berlin",
      'image': "bearded-doctor-glasses.jpg",
      'response': "accepted",
    },
    {
      'name': "Karwan Fatah",
      'specialty': "Cardiologist",
      'degree': "MBBS/MD",
      'hospital': "Charité – Universitätsmedizin Berlin",
      'location': "Germany - Berlin",
      'image':
          "portrait-experienced-professional-therapist-with-stethoscope-looking-camera.jpg",
      'response': "rejected",
    },
    {
      'name': "Kamaran Salar",
      'specialty': "Cardiologist",
      'degree': "MBBS/MD",
      'hospital': "Charité – Universitätsmedizin Berlin",
      'location': "Germany - Berlin",
      'image': "smiling-doctor-sitting-isolated-grey.jpg",
      'response': "accepted",
    },
  ];

  static List<dynamic> hospitals = [
    {
      'name': "Charité – Universitätsmedizin Berlin",
      'location': "Germany - Berlin",
      'type': "Public",
      'phone': "+49 30 450 50",
      'image': "assets/img/hospital/hospital_bg.png",
      'description':
          "Charité – Universitätsmedizin Berlin is one of the largest university hospitals in Europe. With a rich history spanning over 300 years, it combines patient care, research, and teaching at the highest level.",
      'services': [
        "Emergency Care",
        "Inpatient Services",
        "Outpatient Services",
        "Surgery",
        "Diagnostic Imaging",
        "Laboratory Services",
        "Intensive Care",
        "Rehabilitation Services",
      ],
      'illnessTypes': ["Cardiology", "Radiology", "Hematology", "Neurology"],
    },
    {
      'name': "Mayo Clinic",
      'location': "United States - Rochester, Minnesota",
      'type': "Private",
      'phone': "+1 507 284 2511",
      'image': "assets/img/hospital/hospital_bg.png",
      'description':
          "Mayo Clinic is a nonprofit American academic medical center focused on integrated clinical practice, education, and research. It is consistently ranked among the best hospitals in the United States.",
      'services': [
        "Emergency Care",
        "Inpatient Services",
        "Outpatient Services",
        "Surgery",
        "Cancer Treatment",
        "Transplant Services",
        "Diagnostic Imaging",
        "Laboratory Services",
        "Intensive Care",
      ],
      'illnessTypes': ["Oncology", "Cardiology", "Neurology", "Orthopedics"],
    },
    {
      'name': "Johns Hopkins Hospital",
      'location': "United States - Baltimore, Maryland",
      'type': "Private",
      'phone': "+1 410 955 5000",
      'image': "assets/img/hospital/hospital_bg.png",
      'description':
          "Johns Hopkins Hospital is a world-renowned medical institution known for its excellence in patient care, research, and medical education. It has been ranked as one of the top hospitals in the nation for over two decades.",
      'services': [
        "Emergency Care",
        "Inpatient Services",
        "Outpatient Services",
        "Surgery",
        "Transplant Services",
        "Cancer Treatment",
        "Diagnostic Imaging",
        "Laboratory Services",
        "Intensive Care",
        "Rehabilitation Services",
      ],
      'illnessTypes': ["Cardiology", "Neurology", "Psychiatry", "Pediatrics"],
    },
    {
      'name': "Singapore General Hospital",
      'location': "Singapore - Outram",
      'type': "Public",
      'phone': "+65 6222 3322",
      'image': "assets/img/hospital/hospital_bg.png",
      'description':
          "Singapore General Hospital is the largest and oldest hospital in Singapore, providing comprehensive medical care with a focus on patient-centered services and cutting-edge medical technology.",
      'services': [
        "Emergency Care",
        "Inpatient Services",
        "Outpatient Services",
        "Surgery",
        "Diagnostic Imaging",
        "Laboratory Services",
        "Intensive Care",
        "Day Surgery",
        "Rehabilitation Services",
      ],
      'illnessTypes': ["Cardiology", "Oncology", "Orthopedics", "Dermatology"],
    },
    {
      'name': "Cleveland Clinic",
      'location': "United States - Cleveland, Ohio",
      'type': "Private",
      'phone': "+1 216 444 2200",
      'image': "assets/img/hospital/hospital_bg.png",
      'description':
          "Cleveland Clinic is a nonprofit multispecialty academic medical center that integrates clinical and hospital care with research and education. It is consistently ranked among the top hospitals in the United States, particularly known for its cardiac care.",
      'services': [
        "Emergency Care",
        "Inpatient Services",
        "Outpatient Services",
        "Surgery",
        "Heart & Vascular Services",
        "Cancer Treatment",
        "Diagnostic Imaging",
        "Laboratory Services",
        "Intensive Care",
        "Rehabilitation Services",
      ],
      'illnessTypes': ["Cardiology", "Heart & Vascular", "Neurology", "Urology"],
    },
    {
      'name': "Massachusetts General Hospital",
      'location': "United States - Boston, Massachusetts",
      'type': "Private",
      'phone': "+1 617 726 2000",
      'image': "assets/img/hospital/hospital_bg.png",
      'description':
          "Massachusetts General Hospital is a world-renowned medical center known for its excellence in patient care, research, and medical education. It is the largest teaching hospital of Harvard Medical School.",
      'services': [
        "Emergency Care",
        "Inpatient Services",
        "Outpatient Services",
        "Surgery",
        "Cancer Treatment",
        "Transplant Services",
        "Diagnostic Imaging",
        "Laboratory Services",
        "Intensive Care",
        "Rehabilitation Services",
        "Research Services",
      ],
      'illnessTypes': ["Cardiology", "Oncology", "Neurology", "Orthopedics"],
    },
  ];

  static List<Map<String, dynamic>> doctorPatients = [
    {
      'id': 'PAT-1001',
      'name': 'Sarah Ahmed',
      'age': 34,
      'condition': 'Hypertension management',
      'status': 'assigned',
      'lastVisit': '2025-10-12',
      'nextVisit': '2025-11-20 14:30',
      'notes': 'Monitor blood pressure, review medication plan.',
    },
    {
      'id': 'PAT-1002',
      'name': 'Laith Hassan',
      'age': 42,
      'condition': 'Type 2 diabetes follow-up',
      'status': 'assigned',
      'lastVisit': '2025-09-30',
      'nextVisit': '2025-11-25 09:00',
      'notes': 'Assess blood glucose logs and adjust insulin dosage.',
    },
    {
      'id': 'PAT-1003',
      'name': 'Maya Karim',
      'age': 27,
      'condition': 'Physical therapy referral',
      'status': 'assigned',
      'lastVisit': '2025-10-28',
      'nextVisit': '2025-11-22 16:15',
      'notes': 'Post-surgery rehabilitation progress review.',
    },
    {
      'id': 'PAT-1004',
      'name': 'Omar Rahim',
      'age': 56,
      'condition': 'Cardiology consultation',
      'status': 'pending',
      'requestedOn': '2025-11-08',
      'notes': 'New referral awaiting approval.',
    },
    {
      'id': 'PAT-1005',
      'name': 'Dana Karim',
      'age': 29,
      'condition': 'Prenatal consultation',
      'status': 'pending',
      'requestedOn': '2025-11-09',
      'notes': 'First trimester appointment request.',
    },
  ];
}